# Generated by Django 3.0.7 on 2020-10-21 12:56

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='Title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(blank=True, editable=False, null=True)),
                ('Image', models.TextField(blank=True, editable=False, null=True)),
                ('Daily', models.TextField(blank=True, null=True)),
                ('Love', models.TextField(blank=True, null=True)),
                ('Finance', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
