# Generated by Django 3.1.2 on 2020-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_auto_20201109_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
