# Generated by Django 3.1.2 on 2020-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_blogmodel_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signslist',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
