# Generated by Django 3.1.2 on 2020-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_auto_20201119_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
