# Generated by Django 3.1.2 on 2020-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0014_remove_blogmodel_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
