# Generated by Django 3.1.2 on 2020-11-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0015_blogmodel_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='post_views',
            new_name='blog_views',
        ),
    ]
