# Generated by Django 3.1.2 on 2020-11-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0016_auto_20201119_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_views',
        ),
    ]
