# Generated by Django 3.1.2 on 2020-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0017_remove_blogmodel_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_view',
            field=models.IntegerField(default=0),
        ),
    ]
