# Generated by Django 3.1.2 on 2020-11-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0018_blogmodel_blog_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_view',
        ),
    ]
