# Generated by Django 3.1.2 on 2020-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0019_remove_blogmodel_blog_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
